### ISSUE TITLE
Crash on Fabric 1.20.2 with the newest release 2.2.4

### ISSUE THREAD

**Issue by sternschnaube** [Emafire003/ColoredGlowLib#15]
Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'coloredglowlib'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.15.0.jar:?]
	at net.minecraft.server.Main.main(Main.java:109) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[minecraft_server.jar:0.11.2]
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_2561$class_8822
	at me.emafire003.dev.coloredglowlib.config.GsonConfigInstance.<init>(GsonConfigInstance.java:47) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at me.emafire003.dev.coloredglowlib.config.GsonConfigInstance.<init>(GsonConfigInstance.java:32) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at me.emafire003.dev.coloredglowlib.config.ConfigDataSaver.<clinit>(ConfigDataSaver.java:16) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at me.emafire003.dev.coloredglowlib.ColoredGlowLibMod.onInitialize(ColoredGlowLibMod.java:32) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_2561$class_8822
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.15.0.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.0.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at me.emafire003.dev.coloredglowlib.config.GsonConfigInstance.<init>(GsonConfigInstance.java:47) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at me.emafire003.dev.coloredglowlib.config.GsonConfigInstance.<init>(GsonConfigInstance.java:32) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at me.emafire003.dev.coloredglowlib.config.ConfigDataSaver.<clinit>(ConfigDataSaver.java:16) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at me.emafire003.dev.coloredglowlib.ColoredGlowLibMod.onInitialize(ColoredGlowLibMod.java:32) ~[coloredglowlib-2.2.4+fabric_1.20.4.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.0.jar:?]
	... 7 more

(The version is listed on Modrinth for 1.20-1.20.4, or is it just compatible with 1.20.4? Please correct the version listing then 😊)

**Comment by venaminecraft** [comment]
Crash from the Client side:

Mixin apply for mod coloredglowlib failed coloredglowlib.mixins.json:EntityColorMixin from mod coloredglowlib -> net.minecraft.class_1297: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow method method_5781 in coloredglowlib.mixins.json:EntityColorMixin from mod coloredglowlib was not located in the target class net.minecraft.class_1297. Using refmap coloredglowlib-refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow method method_5781 in coloredglowlib.mixins.json:EntityColorMixin from mod coloredglowlib was not located in the target class net.minecraft.class_1297. Using refmap coloredglowlib-refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachShadowMethod(MixinPreProcessorStandard.java:412)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:340)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:299)
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:277)
	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1289)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:294)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:75)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch.getUpper(InterfaceImplTargetPatch.java:86)
	at io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch.getUpper(InterfaceImplTargetPatch.java:95)
	at io.gitlab.jfronny.libjf.unsafe.asm.patch.targeting.InterfaceImplTargetPatch.apply(InterfaceImplTargetPatch.java:24)
	at io.gitlab.jfronny.libjf.unsafe.asm.AsmTransformer.transformClassBytes(AsmTransformer.java:91)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at carpet_autocraftingtable.AutoCraftingTable.<clinit>(AutoCraftingTable.java:19)
	at net.minecraft.class_128.handler$boj000$carpet-autocraftingtable$gameStarted(class_128.java:515)
	at net.minecraft.class_128.method_24305(class_128.java)
	at net.minecraft.client.main.Main.main(Main.java:167)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by Emafire003** [comment]
Oops, sorry wrong version numbering please use the previuos version, there are no other changes beside the compatibility with 1.20.3/4!

Nvm, i'll release a specifc version for 1.20.2 shortly

**Comment by venaminecraft** [comment]
That's awesome, thank you so much 😊
