### ISSUE TITLE
Weird server log

### ISSUE THREAD

**Issue by ghost** [Emafire003/ColoredGlowLib#7]
[11:23:16] [Server thread/INFO]: Getting variables values from the data file...
[11:23:16] [Server thread/ERROR]: There was an error while reading on the file
[11:23:16] [Server thread/INFO]: [STDERR]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:975)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:928)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:877)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at me.emafire003.dev.coloredglowlib.util.DataSaver.getDefaultColor(DataSaver.java:190)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at me.emafire003.dev.coloredglowlib.ColoredGlowLib.getValuesFromFile(ColoredGlowLib.java:186)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at me.emafire003.dev.coloredglowlib.ColoredGlowLib.lambda$new$1(ColoredGlowLib.java:56)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$2(ServerLifecycleEvents.java:49)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.handler$edj000$afterSetupServer(MinecraftServer.java:14301)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[11:23:16] [Server thread/INFO]: [STDERR]: Caused by: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 2 path $
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:824)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:380)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.internal.bind.TypeAdapters$15.read(TypeAdapters.java:368)
[11:23:16] [Server thread/INFO]: [STDERR]: 	at com.google.gson.Gson.fromJson(Gson.java:963)
[11:23:16] [Server thread/INFO]: [STDERR]: 	... 10 more

No crash, but curious about it:)

**Comment by Emafire003** [comment]
Yeah it means something is messed up with the coloredglowlib_data.json file. If you updated to a new version of coloredglowlib and didn't update the file that may be the cause

**Comment by ghost** [comment]
Hello @Emafire003,

sorry for the late response. I was simple trying to delete the config folder.
But the error is still persistent - huh.
Using FoxGlow v1.5.0 and ColoredGlowLib v2.0.1.
(Only Forge has a v2.0.2 - but this leads to something Forge specific I think.)

**Comment by Emafire003** [comment]
Yeah I think I forgot to modify something on the datasaver then, but I think it should still be working so I'll fix it when I have time sorry

**Comment by ghost** [comment]
Good to know:)
Nothing is broken, just a weird log result.
Thanks for your work.
